### ISSUE TITLE
Make the external object instance a parameter?

### ISSUE THREAD

**Issue by harmanpa** [modelica-3rdparty/ExternData#11]
Is there a specific reason the external object instance is not a parameter? For example:
`protected
      Types.ExternXLSFile xls=Types.ExternXLSFile(fileName, encoding);`
could be:
`protected
      parameter Types.ExternXLSFile xls=Types.ExternXLSFile(fileName, encoding);`
I'm using Dymola and it doesn't allow the calling of the functions such as getReal() to set parameters if the external object isn't a parameter.

**Comment by tbeu** [comment]
Well, I tested with Dymola and it should work.

Can you please add a small example such that I can reproduce it.

The reason is that we have the object construction the same way for [ModelicaStandardTables](https://github.com/svn2github/Modelica_StandardLibrary/blob/master/Modelica/Blocks/Tables.mo#L33-L39).

**Comment by harmanpa** [comment]
I was surprised, because I thought it would make it a parameter if possible (other Modelica compilers I know do this...), however using the current master and uncommenting the Examples I get this error for XMLTest2:

> The variability of the definition equation:
> gain.k = xmlfile.getReal_Unique'"xmlfile"'(
> "set2.gain.k", 
> xmlfile.xml);
> is higher than the declared variability of the variables.

**Comment by tbeu** [comment]
Strange. Which Dymola version exactly (Have 2015 and 2016 for test)? Need to check it.

**Comment by tbeu** [comment]
[This](https://github.com/tbeu/ExternData/blob/master/ExternData/package.mo#L219) reminds me: Need to make the examples clearer.

**Comment by tbeu** [comment]
Small MSL test for you. Does [M.mo](https://gist.github.com/tbeu/c2643d8f8a11b4a64ffc9f6ff92b96ee) work for your Dymola tool? Works in Dymola 2016. But should make the same issue apparent - probably.

**Comment by harmanpa** [comment]
That test is working fine. But XMLTest2 is failing for me with the same error in Dymola 2015, 2016 and 2017. The release version works fine, but for that the external object instance is declared as `inner parameter`.

**Comment by tbeu** [comment]
Thanks for confirming. Guess I need to revert to `parameter` and make a new release. There have been some bugs fixed since [v.1.1.0](https://github.com/tbeu/ExternData/releases/tag/v1.1.0) thus I recommend to use the current HEAD version and manually changing it to `parameter`. PR is welcome.

**Comment by tbeu** [comment]
The new major update [v2.0.0](https://github.com/tbeu/ExternData/releases/tag/v2.0.0) was released today with many bug fixes, simplified examples, a user's guide and a more liberate license.
