### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by christiankral** [modelica-3rdparty/ExternData#14]
Do have any plans to implement CSV functionality in the ExternData library the future?

**Comment by tbeu** [comment]
Yes, I had such plans to add CSV support. I evaluated [libcsv](https://github.com/robertpostill/libcsv) but unfortunately it is LPGL, thus I am not sure if I can use it.

**Comment by tbeu** [comment]
See https://github.com/robertpostill/libcsv/issues/3 for the license question of libcsv.

**Comment by tbeu** [comment]
Well, I guess I do not need to rely on libcsv and can easily do it myself. So yes, I'll add it.

**Comment by tbeu** [comment]
Which function do you need more? Function getReal (to retrieve single scalar Rela value) or getRealArray2D (to retrieve Real matrix)?

**Comment by christiankral** [comment]
Thanks for working on the CSV implementation. To me the getRealArray2D function is the more important one since I am planning to process different simulations with the parameters stored in CSV files (actually tab separated).

**Comment by tbeu** [comment]
OK, will add getRealArray2D, also for XLS and XLSX.

**Comment by tbeu** [comment]
@christiankral Can you please test if the current implementation does what you would expect from it? Thanks.

**Comment by christiankral** [comment]
I tried to run the included example ExternData.Examples.CSVTest but the file `ED_CSVFile.h` was missing.

**Comment by tbeu** [comment]
It is in the standard Include directory: https://github.com/tbeu/ExternData/tree/master/ExternData/Resources/Include

**Comment by christiankral** [comment]
OK I see. For some reason the copy from the GitHub repository to my local work directory missed this file... However, when running the example ExternData.Examples.CSVTest an error is triggered by Dymola that I cannot understand:
```
Compilation of ExternData.Examples.CSVTest failed.

Note: There were translation errors that might explain the problem.

Compiler message:
dsmodel.c: In function ‘ExternData_Types_ExternCSVFile_destructor_M’:
dsmodel.c:95:8: error: ‘ED_destroyINI’ undeclared (first use in this function)
(ED_destroyINI)(csv0_0);
^
dsmodel.c:95:8: note: each undeclared identifier is reported only once for each function it appears in
/opt/dymola-2017FD01-x86_64/source/matrixop.c: In function ‘Integer2String’:
/opt/dymola-2017FD01-x86_64/source/matrixop.c:3580:14: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘int’ [-Wformat=]
sprintf(buf,"%*.*ld",(int)minwidth,(int)precision,(int)x);
^
/opt/dymola-2017FD01-x86_64/source/matrixop.c: In function ‘Integer2String2’:
/opt/dymola-2017FD01-x86_64/source/matrixop.c:3601:28: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);
^
/opt/dymola-2017FD01-x86_64/source/matrixop.c:3601:36: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
sprintf(buf,leftJustified?"%-*ld":"%*ld",(int)minwidth,(int)x);
^
In file included from /opt/dymola-2017FD01-x86_64/source/matrixop.c:3747:0:
/opt/dymola-2017FD01-x86_64/source/localeless.cpp: In function ‘sscanfCx2_underscore’:
/opt/dymola-2017FD01-x86_64/source/localeless.cpp:316:22: warning: format ‘%lx’ expects argument of type ‘long unsigned int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
return sscanf(line, "%lx_%lx", a,b);
^
/opt/dymola-2017FD01-x86_64/source/localeless.cpp:316:22: warning: format ‘%lx’ expects argument of type ‘long unsigned int *’, but argument 4 has type ‘unsigned int *’ [-Wformat=]
/opt/dymola-2017FD01-x86_64/source/localeless.cpp: In function ‘sscanfClu’:
/opt/dymola-2017FD01-x86_64/source/localeless.cpp:327:22: warning: format ‘%lu’ expects argument of type ‘long unsigned int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
return sscanf(line, "%lu", a);
^

Errors were found
```
OpenModelica is not comiling either

**Comment by tbeu** [comment]
Hang on. I've just detected it. Sorry for that.

**Comment by tbeu** [comment]
Can you pull and test again.

**Comment by christiankral** [comment]
OK I pulled the new version an re-simulated the example. I see the very same error message again (double checked it)

**Comment by tbeu** [comment]
Argh! Too much copy-pasted. Should be fixed by now.

**Comment by christiankral** [comment]
The examples now compiles but generates a runtime error:
```
... loading "/home/data/work/ExternData/Resources/Examples/test.csv"
The following error was detected at time: 0
Error in line 0: Cannot read double value "0
" from file "/home/data/work/ExternData/Resources/Examples/test.csv"

The stack of functions is:
csvfile.getRealArray2D_Unique'"csvfile"'
csvfile.getRealArray2D_Unique'"csvfile"'(
3, 
2, 
1, 
csvfile.csv)
Error: Failed to start model.
```

**Comment by tbeu** [comment]
Oh, I love those different line endings.

**Comment by tbeu** [comment]
Should be fixed. Tested on Win and Linux.

**Comment by christiankral** [comment]
I tried it on my computer and it worked fine. This is great. Thanks a lot for supporting CSV files in your library. 

May I make a feature suggestion: It sometimes is convenient to start reading the 2D real array starting from a certain row (that is supported by the parameter line) and column. In case I have strings left of numeric data array I were not able to read the numeric data with the actual implementation. It were thus very useful to also support a starting row for reading the 2D real array. This additional feature would also be in line with, e.g. the XLS and XLSX functionality, where the starting cell is specified.

**Comment by tbeu** [comment]
Thanks for confirming the test.

Yes, I also thought about a starting field, similar as with the Excel files. I only added the row parameter but missed the column parameter. I'll rename `line` to `startField`={1,1} and add it.

**Comment by tbeu** [comment]
Please pull and test again.

**Comment by christiankral** [comment]
I tested the new feature and it works fine. This is great. Thanks for your development.

**Comment by tbeu** [comment]
Thanks for your feedback. One thing which is not supported are line breaks within record fields (which is allowed on CSV if enclosed by quotes).
