### ISSUE TITLE
Error compiling example with dymola 2017 FD01

### ISSUE THREAD

**Issue by njhawk71** [modelica-3rdparty/ExternData#15]
Hi tbeau!  Thanks for putting this together.  It's just what I need for a Dymola project I'm working on.  

Background info: 
I'm using Dymola 2017 FD01 with Visual C++ 2015 "Community" Compiler

The Error Message in Dymola that is thrown during compilation:
      Compiling and linking the model (Visual C++). 
 
      dsmodel.c
      c:\..........\github - externdata\externdata\resources\include\msvc_compatibility.h(60): 
      error C2084: function 'FILE *__iob_func(void)' already has a body
      c:\program files (x86)\dymola 2017 fd01\source\dsutil.h(1958): 
      note: see previous definition of '__iob_func'
 
      Error generating Dymosim.

I can see that each file listed has the function defined in it... so it makes sense that there is a conflict, but I'm unsure of what I should do to correctly "fix" it.

Any chance you can take a look?

Cheers!

**Comment by tbeu** [comment]
Ah, they added it for Dymola 2017 FD01.

Can you please check if the following works for you:
```diff
--- a/ExternData/Resources/Include/msvc_compatibility.h
+++ b/ExternData/Resources/Include/msvc_compatibility.h
@@ -48,6 +48,7 @@ static void Timezone_initialize(void) {
 }
 #endif
 
+#if !defined(HACK_SUPPORT_VS2015)
 extern FILE _iob[3];
 
 #undef stdin
@@ -60,6 +61,7 @@ extern FILE _iob[3];
 FILE* __iob_func(void) {
 	return _iob;
 }
+#endif
 
 #pragma comment( lib, "legacy_stdio_definitions.lib" )
 
```
Thanks.

**Comment by njhawk71** [comment]
Yep, that did it! 

FYI- Couldn't use your inserts verbatim... had to add a # in front of the initial if statement... caught it in the syntax highlight before running.

Thanks!

**Comment by tbeu** [comment]
Thanks for confirmation. The missing `#` actually was an error. I edited the previous comment.
