### ISSUE TITLE
Library of dependencies not found

### ISSUE THREAD

**Issue by Sarasrv** [modelica-3rdparty/ExternData#16]
Hi

While loading this External data to SimulationX the Examples\package.mo won't load. What can I do?
And most importantly This is affecting the library usage
![screen shot 2017-05-09 at 14 02 42](https://cloud.githubusercontent.com/assets/28565784/25852273/b45b6688-34c0-11e7-9905-d8c7b54dd059.png)

**Comment by tbeu** [comment]
1. What is the exact error message in the output window?
1. Did you add C:\Users\Sara\Desktop\SIMX PROJECTS\ExternData-2.2.0 to the MODELICAPATH? You can do so by menu Extras -> Options -> Directories -> Modelica Search Path (MODELICAPATH).

**Comment by Sarasrv** [comment]
Thak you for your response. I have done all of those. 
Here are some screenshots:

![screen shot 2017-05-09 at 15 03 20](https://cloud.githubusercontent.com/assets/28565784/25854781/28815420-34c9-11e7-9623-b70e67e36c5b.png)

**Comment by Sarasrv** [comment]
and here is the message I get when I try to open my previous project:
![screen shot 2017-05-09 at 15 08 39](https://cloud.githubusercontent.com/assets/28565784/25854893/86ec76ac-34c9-11e7-8c88-73d049783a93.png)

**Comment by tbeu** [comment]
What is the exact error message in the output window? You can see it if you enable it by menu View ->Output Bar.

**Comment by Sarasrv** [comment]
Here it is:
![screen shot 2017-05-09 at 15 20 41](https://cloud.githubusercontent.com/assets/28565784/25855455/240642aa-34cb-11e7-90d2-eb4a9eab9a3f.png)

**Comment by tbeu** [comment]
Please add C:\Users\Sara\Desktop\SIMX PROJECTS\ExternData-2.2.0 to the MODELICAPATH, not C:\Users\Sara\Desktop\SIMX PROJECTS\ExternData-2.2.0\ExternData.

**Comment by Sarasrv** [comment]
Many thanks for the help. That worked. But now I get another error when running my existing simulation: 

![screen shot 2017-05-09 at 16 21 33](https://cloud.githubusercontent.com/assets/28565784/25858484/c2866498-34d3-11e7-8d01-7260dbf66e21.png)

**Comment by tbeu** [comment]
I tested ExternData.Examples.XLSTest in SimulationX 3.8.2.45334 x64 successfully. Can you please test if ExternData.Examples.XLSTest works for you.

**Comment by Sarasrv** [comment]
Could you please tell me how to do it?

**Comment by Sarasrv** [comment]
Here is the code I have in this model:
![screen shot 2017-05-10 at 13 54 32](https://cloud.githubusercontent.com/assets/28565784/25899581/48ca27b0-3588-11e7-9585-4512293ed47a.png)

**Comment by Sarasrv** [comment]
Just a quick update: The Externaldata 2.2 and Master are missing the ITI_ED_XLSFile.dll file. hence the error. 
I used package 2.1 and it worked!
