### ISSUE TITLE
Unit testing package

### ISSUE THREAD

**Issue by hyumo** [modelica-3rdparty/ExternData#24]
As more and more features are added to the library, I am thinking we should start thinking to add a unit testing library based on [XogenyTest](https://github.com/xogeny/XogenyTest). Current example models are great, but they are not covering all functions and features.

**Comment by hyumo** [comment]
I can start making the library if needed

**Comment by tbeu** [comment]
> Current example models are great, but they are not covering all functions and features.

That is true, for example I tested (and fixed) the newly added JSON functions all manually (and added a few only to the test model).

I also considered unit tests but did not yet start with. In general, I prefer to not have the unit tests on Modelica but on C level only. This way, I can easily run it on Travis CI. We just need a new make target, some test C files and basically that's it. So if you are keen to write the unit tests I appreciate your effort.

**Comment by hyumo** [comment]
Yeah, same thing here, I use xml reader the most and I test all the xml features myself by creating different cases in sample xml files. With all these new features added, I guess I will have to run these tests again, which brought me the idea that we need a unit testing library. I will try to build it in my spare time and see how far I can go.

I am not sure how Buildings library figured out the solution to run their tests in TravisCI, but I think with unit tests implemented in Modelica, it helps to avoid different tool supporting issue.

**Comment by tbeu** [comment]
Buildings lib uses preconfigured docker builds with licensed Dymola or JModelica.org installed.

Looks like I need to add getArraySize1D/2D for xml too.

**Comment by hyumo** [comment]
OK, that makes sense. The authors of Building lib must be paying for the license cost themselves, I wonder if Dymola/SimulationX would provide any free licenses for open source projects like ExternData?

I wrote an in house testing framework for our own CI server, the licensing stuff is really a pain, I can only kick it off at night when nobody is using the server license, which looks more like "dis-continuous" integration.

**Comment by tbeu** [comment]
SimulationX Student Edition is able to run small enough models (e.g. all models of ExternData.Examples or similar small unit test models). Dymola Trial Version is also able to run small enough models, but only allows one external function, which kicks out all the external objects (having ctor, dtor and object functions).
