### ISSUE TITLE
cannot find cell value

### ISSUE THREAD

**Issue by KjartanVdB** [modelica-3rdparty/ExternData#31]
I tried to change the cellAddress in the example: XLSXTests, from B2 to C2. I added a value in cell C2. However I get the message:

Cannot get cell (1,2) in sheet "set1" from file "C:/.../test.xlsx"

**Comment by overtaker** [comment]
Can you attach the edited file here.

**Comment by KjartanVdB** [comment]
[test.xlsx](https://github.com/modelica-3rdparty/ExternData/files/2705248/test.xlsx)

**Comment by overtaker** [comment]
Cannot reproduce. The value `3` is extracted as expected.

Could it be some problem with regional settings?
