### ISSUE TITLE
Compilation fails in Dymola 2019 FD01 with MinGW GCC

### ISSUE THREAD

**Issue by kiddjmadd** [modelica-3rdparty/ExternData#32]
Hello,
Posting under 2.4 since I'm still running MSL 3.2.2. When trying to run the examples I get errors similar to following:

Compiler message:

Compiling and linking the model (GCC). 

Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
C:/Program Files/Dymola 2019/Modelica/Library/ExternData-2.3.3/ExternData/Resources/Library/win32\ED_CSVFile.lib(Release Lib/ED_CSVFile/ED_CSVFile.obj):(.text[_ED_createCSV]+0x1d3): undefined reference to `_create_locale'
C:/Program Files/Dymola 2019/Modelica/Library/ExternData-2.3.3/ExternData/Resources/Library/win32\ED_CSVFile.lib(Release Lib/ED_CSVFile/ED_CSVFile.obj):(.text[_ED_destroyCSV]+0x2f): undefined reference to `_free_locale'
collect2.exe: error: ld returned 1 exit status

**Comment by overtaker** [comment]
I am afraid that GCC support was not tested and is not available out-of-the-box. Do you have any chance to install a (free) Visual Studio compiler?

**Comment by kiddjmadd** [comment]
My company installed VS 2019 for another project and all examples work with that compiler, so you're correct this is a mingw compatibility issue.
