### ISSUE TITLE
GCC compatiblitiy

### ISSUE THREAD

**Issue by cid219** [modelica-3rdparty/ExternData#33]
I see these libs are not compatible with GCC per this thread:

 https://github.com/modelica-3rdparty/ExternData/issues/32 

but I'm wondering if there is anything preventing me from recompiling these libs with GCC after editing the make files? Was the decision to not include GCC compatibility intentional due to some restriction or was it just a convenience?

**Comment by beutlich** [comment]
It's just convenience, I am afraid.
