### ISSUE TITLE
Fix problem with tir file example

### ISSUE THREAD

**Issue by hhammondscott** [modelica-3rdparty/ExternData#35]
We use the ExternData.TIRFile to read .tir files, but since the latest change to the library in revision 621 (updating binaries) this no longer works. The same error is seen in your example ExternData.Examples.TIRTest.

**Comment by overtaker** [comment]
I am sorry. I forgot my custom INI configuration when updating ini.h by 5c2cde739c7a83540d624c5d7380b69b247feab7. Going to release a new version 2.6.1 immediately.
