### ISSUE TITLE
throw error when variable not found

### ISSUE THREAD

**Issue by Mathadon** [modelica-3rdparty/ExternData#36]
The line https://github.com/modelica-3rdparty/ExternData/blob/2fb7395115cc109b29813876c0f606af3ab84ac3/ExternData/Resources/C-Sources/ED_JSONFile.c#L136 throws a message when a double cannot be found in a json file. It seems that the function then returns 0 as a default for that variable. When this message is overlooked by the user, it can result in completely wrong results that may go unnoticed. I would suggest to use `ModelicaFormatError` instead of `ModelicaFormatMessage`, or at least provide this as an optional flag. Note that for arrays an error is already thrown: https://github.com/modelica-3rdparty/ExternData/blob/2fb7395115cc109b29813876c0f606af3ab84ac3/ExternData/Resources/C-Sources/ED_JSONFile.c#L356

**Comment by tbeu** [comment]
That was changed to ModelicaFormatMessage by purpose for #21 in the lack of any better ideas, see especially https://github.com/modelica-3rdparty/ExternData/issues/21#issuecomment-320467150. There is a Boolean output argument signaling if a scalar variable is found or not.

**Comment by tbeu** [comment]
Reading my old commit message of bde9869be2cb236b29b84c3aae1457e8275db649 again I might change the message to ModelicaFormatWarning though.

**Comment by Mathadon** [comment]
In `ExternData.Functions.JSON.getReal` there could be an optional input `generateError` with default `false`? And based on that value you could decide whether to throw an error or a message (preferably warning, indeed).

**Comment by tbeu** [comment]
You can workaround this use case by checking the output argument `exist` of function ExternData.Functions.JSON.getReal and call Modelica.Utilities.Streams.error if it is set to false.

**Comment by Mathadon** [comment]
That indeed seems to be a valid workaround, but it is not that elegant (requires multiple lines of Modelica code). Is there something wrong with my suggestion?

**Comment by tbeu** [comment]
No, nothing wrong, except that I'd make it an enumertaion argument with values "No message", "Debug message", "Warning message" and "Error message". The other point is that it will require quite some time to do it in a consistent way for all functions provided by ExternData.

**Comment by Mathadon** [comment]
Let's see if I can help out.. If you can make a prototype implementation then I can replicate it for all JSON functions?

**Comment by tbeu** [comment]
It is not only JSON, but let me think about it.

**Comment by Mathadon** [comment]
I figured, but I rather not spend 10h on it either 😅 If the JSON ends up not being too much work then I might do all of them, but no promises there.

**Comment by Mathadon** [comment]
Any update on this? :)

**Comment by tbeu** [comment]
I am surprised that the proposed workaround did not work out for you. Nevertheless, the diagnostic behaviour for missing data is a configuration parameter now.

**Comment by Mathadon** [comment]
This works great, thanks a lot!
