### ISSUE TITLE
CSVTest causing a translation and scripting error in OpenModelica 

### ISSUE THREAD

**Issue by songkuku** [modelica-3rdparty/ExternData#41]
Hello. 

I am currently using OpenModelica v1.18.0 and complex 4.0.0.
I successfully include the ExternData into my OpenModelica system libraries.
However, the CSVTest does not run and shows error messages as shown below:

[4] 16:48:44 Translation Error
[ExternData: 53:3-77:14]: Ignoring record component:
  ExternalObject ExternData.Types.ExternCSVFile csv;
when building the record constructor. Records are allowed to contain only components of basic types, arrays of basic types or other records.

[5] 16:48:44 Scripting Error
[ExternData.Examples: 35:5-35:89]: [The default value of csv causes a cyclic dependency.](omeditmessagesbrowser:///ExternData.Examples?lineNumber=35)

[6] 16:48:44 Translation Error
Error occurred while flattening model ExternData.Examples.CSVTest

It seems like there's another person who's having a similar issue (https://stackoverflow.com/questions/67967920/externdata-library-with-open-modelica).
It would be very grateful if you could have a look at this issue.
Thank you :) 

Best,

**Comment by dietmarw** [comment]
I just tested it with OpenModelica 1.19.0~dev-706-ga9a3aa6 (latest nightly) on Linux and it works fine. I think to remember that there was/is an issue with the Windows support but it is more related to OpenModelica than ExternalData if I'm not mistaken.

**Comment by songkuku** [comment]
@dietmarw thanks a lot for your prompt reply. However, my colleague who's using OpenModelica in Windows and the same v1.18 and complex 4.0.0 has no problem. That's why the error messages might be Windows-specific issue...

**Comment by beutlich** [comment]
ExternData.Examples.XMLTestReadDim demonstrates a workaround if the record interface do not work. You might try (and adapt it) in your environment.

Otherwise it seems odd why your and your colleague's observation differ given the identical environment.

**Comment by songkuku** [comment]
I found the reason: I was using an old front-end. Once switching to the new front-end, the issue was solved. 
Thanks a lot for all your answers :)
