### ISSUE TITLE
SimulationX binaries does not fit anymore

### ISSUE THREAD

**Issue by gkurzbach** [modelica-3rdparty/ExternData#42]
In the meantime SimulationX has changed and also the VisualStudio used went to VS 2019 so the dll given does not run properly anymore.

Using the project file in Resources/BuildProjects/VisualStudio2010
I tried to use the 2010 tooset in VS2019 and I got the error:
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_xmlValidNormalizeString" in Funktion "_xmlRemoveID".

I tried to compile the sources with VS 2019 compiler and I got the error 
ED_XML2File.obj : error LNK2001: Nicht aufgelöstes externes Symbol "_iob".

additionally.

How to compile the Library with Visual Studio?

**Comment by beutlich** [comment]
I really wonder why the libraries (compiled by VS 20210) can no longer be loaded by SimulationX. This is main issue that should be addressed.

* It used to work with SimulationX 4.2 and 4.3.
* Modelica_DeviceDrivers also is compiled by VS 2010 and used to work.

What is the actual error message?

**Comment by gkurzbach** [comment]
After defining HACK_SUPPORT_VS2015 globaly and LIBXML_VALID_ENABLED at some places it compiled finally. At the end it was not an issue of the library but in SimulationX but I had it to debug somehow. Nonetheless it could be made easier to compile the library with newer versions of Visual Studio.
Thanks and best wisches, Gerd.

**Comment by beutlich** [comment]
> and LIBXML_VALID_ENABLED at some places

Done by 85d824705e8ca162e601c9585306e7097d46decc. No need to disable it.
