### ISSUE TITLE
Dymola 2024x Refresh 1 Beta 1 - Experiments using ExternData will not compile

### ISSUE THREAD

**Issue by NateHorn** [modelica-3rdparty/ExternData#48]
While running tests on Dymola 2024x Refresh 1 Beta 1 we found that our models referencing ExternData will no longer compile.

This is the compiler message:

![image](https://github.com/modelica-3rdparty/ExternData/assets/33639937/ec89cb6d-1031-4274-9066-7a4b651ede95)

 __iob_func is located in msvc_compatibility.h and appears to be there to support some older versions of Visual Studio compilers. 

Support for compilers 2012 (and earlier) will not be supported by Dymola 2024x Refresh1 (per the Dymola developers)

It appears that this chunk of code is gone in the newest version of dsutil.h:

![image](https://github.com/modelica-3rdparty/ExternData/assets/33639937/6bec40b4-7d6b-43bd-9092-ce2401724f26)

**Comment by beutlich** [comment]
Thanks for reporting early during Dymola beta testing.

@HansOlsson Is there some Dymola version macro defined such that I can a add a switch to msvc_compatibility.h when to define __iob_func and when not. This way I can support newest and older Dymola versions. Thank you.

**Comment by HansOlsson** [comment]
> Thanks for reporting early during Dymola beta testing.
> 
> @HansOlsson Is there some Dymola version macro defined such that I can a add a switch to msvc_compatibility.h when to define __iob_func and when not. This way I can support newest and older Dymola versions. Thank you.

We are investigating.

The best solution would be to avoid the need for it by not _directly_ using stdin/stdout/stderr (when compiling with VS 2005 (well anything up to VS 2012)). However, it seems that it is integrated at a low level in libxml2 (and possibly other modules).

With directly I mean that `fprintf(stdout, ....)` directly use `stdout` and is problematic, but `printf(...)` only use it indirectly and is thus fine.

**Comment by hhammondscott** [comment]
In the released version of Dymola 2024x Refresh 1 there is a new flag **Advanced.Translation.LinkWithIobFuncStub** to address this problem I think. It is set to false by default, but when changed to true the experiments using ExternData that @NateHorn mentioned above will compile again.

**Comment by beutlich** [comment]
@hhammondscott Thanks or the feedback and test. Do you know if there is some Dymola feature to set this flag by default whenever ExternData is utilized?

**Comment by hhammondscott** [comment]
Sadly I'm not aware of any feature in Dymola that would allow this flag to be set to true whenever ExternData is used. In other libraries where flags need to be set, I've seen them include functions to set the flags or add the flag settings to the Dymola startup script. We've added the flags to the model annotations in the experiments which use ExternData, using __Dymola_experimentFlags(Advanced(Translation(LinkWithIobFuncStub=true))).

**Comment by beutlich** [comment]
@HansOlsson @hhammondscott Thanks for the feedback! Resolved by cbe184f6f8cf9f0174f0084558012fe9d304e954.
