### ISSUE TITLE
Update license for bsxml-json

### ISSUE THREAD

**Issue by t-sommer** [modelica-3rdparty/ExternData#50]
bslxml-json is licensed under the [GPLv2](https://github.com/bsapundzhiev/bsxml-json/blob/master/COPYING) (see also the discussion in https://github.com/bsapundzhiev/bsxml-json/issues/1).

However, 

- https://github.com/modelica-3rdparty/ExternData/blob/master/ExternData/Resources/Licenses/Third-party/LICENSE_bsxml-json.txt , and 
- https://github.com/modelica-3rdparty/ExternData/blob/master/ExternData/Resources/C-Sources/bsxml-json/COPYING, as well as the
- source files

 contain what seems to be a non-standard "1-clause" BSD license.

**Comment by beutlich** [comment]
While you cited https://github.com/bsapundzhiev/bsxml-json/issues/1 it seems you missed the follow-up issue https://github.com/bsapundzhiev/bsxml-json/issues/12 where it is confirmed by bsxml-json author in https://github.com/bsapundzhiev/bsxml-json/issues/12#issuecomment-153327004 that any license can be used as long as the bsstr code is not used. Consequently bsstr was removed by c24a3145353adfcaae7050169fef25ee9f6cd115 to comply with the non-GPL license.

I consider this as clarified.
