### ISSUE TITLE
XLSXFile reading from wrong sheet and doesn't handle equations

### ISSUE THREAD

**Issue by dBriantClaytex** [modelica-3rdparty/ExternData#51]
Hi,

I have been working with ExternData within Dymola attempting to read in an .xlsx file and have come across a couple of issues.

- When reading from the first sheet it attempts to read from the second sheet, but in the correct location.
- When it attempts to read from the second sheet, it causes an error as it's reading a very simple calculation (A3-A2) instead of providing the result of the calculation.

Both of these issues do not exist when converted to an xls, but using that format doesn't allow the data size that this project requires.

The attached model demonstrates the issue, with both the xlsx and the .mo files.
[ExternDataXLSXBug.zip](https://github.com/user-attachments/files/18210442/ExternDataXLSXBug.zip)

Many thanks,
David

**Comment by dBriantClaytex** [comment]
Hi,

Further tests reveal a different error occuring when using a brand new xlsx spreadsheet, but with the same content as previous post, tested within Dymola.

In this instance, the simulation freezes at initialisation if a correct file read is called, the example is attached.
[XLSXFromScratchBug.zip](https://github.com/user-attachments/files/18211789/XLSXFromScratchBug.zip)


Many thanks,
David

**Comment by beutlich** [comment]
Thanks for reporting. Need to debug (using Dymola )whats going on.

**Comment by beutlich** [comment]
After checking the provided test cases I observed three issues:

1. Access violation on destruction of the external object if "xl/sharedStrings.xml" is missing the XLSX file.
1. Programming error on sheet name resolution.
1. Unimplemented case of formula values.

All three issues could be fixed.

**Comment by dBriantClaytex** [comment]
Hi Both,

Thank you for the very fast response, I appreciate you looking at this.

Just to be clear, is it a problem with the .XLSX file examples I sent? As I am still experiencing the issues with the examples I sent after pulled the updated externData both on Dymola 2024x Refresh 1 and 2025.

Many thanks,
David

**Comment by overtaker** [comment]
No, the provided XLSX files are good examples.

Did you actually rebuild the binaries? For Linux they are provided at: 
https://bitbucket.org/tbeu/downloads/downloads/ExternData_linux64.tar.xz

Am 2025-01-02 12:30, schrieb dBriantClaytex:
> Hi Both,
> 
> Thank you for the very fast response, I appreciate you looking at this.
> 
> Just to be clear, is it a problem with the .XLSX file examples I sent? 
> As I am still experiencing the issues with the examples I sent after 
> pulled the updated externData both on Dymola 2024x Refresh 1 and 2025.
> 
> Many thanks,
> David

**Comment by dBriantClaytex** [comment]
I am running in windows.

For clarity, the steps taken:
- Cleared the Dymola working directory
- Deleted the old externData files
- Replaced with the extracted new ones
- Checked that the files used when opening in Dymola are the correct ones (checked the new license agreement date 2025 and checked ED_XLSXFile.c line 368 for changes made in your latest commit)
- Ran the attached examples and the same errors occured.

Apologies if I am missing a step to cause the new library to work

**Comment by beutlich** [comment]
I did not yet update the new binaries, hence you observe the same old errors since the same old binaries are used.

For now, you can checkout the [update-binaries](https://github.com/modelica-3rdparty/ExternData/tree/update-binaries) branch where I just pushed the rebuilt Windows binaries.

**Comment by dBriantClaytex** [comment]
Brilliant, Thank you, it now works as expected.

I really appreciate the very quick and great help.
