### ISSUE TITLE
Suggestion: saving .mat time series data in CombiTimeTable format

### ISSUE THREAD

**Issue by Mathadon** [modelica-3rdparty/ExternData#8]
Hi,

it would be useful to have a block that saves time series data to a .mat file while simulating. The block should have arrays of real/boolean/integer inputs, and for each input a corresponding parameter for the variable name. The input values can then be saved at regular time intervals `T`. The output should be a .mat file in a format that can be read by `Modelica.Blocks.Sources.CombiTimeTable`. This allows the creation of time series data that can be used again later in a different model.

Is this something that would fit in this library? Or possibly this exists already?

Thanks!

**Comment by tbeu** [comment]
Actually I have this ready as inhouse block with either sample-based output or storage after each valid solver step (tool-dependent and not in compliance with Modelica, I know). The problem with MAT files is the column-major storage, thus in each call to the external function the old array is read from MAT file, transposed, dimension incremented, old values copied, new values added, transposed again and saved back to file. The other possibility is to store all values in auxiliary buffers within the external object and only write the array to file in a terminal call.

**Comment by Mathadon** [comment]
I would also suggest to use a buffer. You could also parametrize the buffer to store the results 'every x samples'?

**Comment by tbeu** [comment]
Yes, that is also possible.

**Comment by tbeu** [comment]
For a clean solution the sample feature of the synchronous elements would be required, which is not supported by many tools. I'll close this one as wont-fix. Sorry for that.

**Comment by Mathadon** [comment]
Okay!
