### ISSUE TITLE
Make library working in OpenModelica

### ISSUE THREAD

**Issue by tbeu** [modelica-3rdparty/ExternData#9]
@sjoelund Whereas the library works in Dymola and SimulationX, it is currently not working with OM as stated (again) at [SO](http://stackoverflow.com/a/34641880/610990). Please see the [ExternData.Examples.XMLTest1](https://github.com/tbeu/ExternData/blob/OM-test/ExternData/package.mo#L219-L230) from the OM-test branch for a simple test.

What shall I do to make it compatible with OM? Or is this a issue of OM itself?

@dietmarw Thanks for the SO link.

**Comment by dershow** [comment]
Here is the error that I get when I try to run XMLTest1 in OM:

[1] 11:22:13 Scripting Error
[ExternData.UsersGuide: 193:9-193:48]: The default value of xml causes a cyclic dependency.

[2] 11:22:13 Translation Error
Error occurred while flattening model ExternData.Examples.XMLTest1

**Comment by tbeu** [comment]
Thanks. Which version did you test with? OM-test head or released vs.?
Hopefully @sjoelund can give me some insight in both issues.

**Comment by dershow** [comment]
Just now, I tested with OM-devel 1.9.4~dev-627.  I also got the same results on 1.9.4~dev-59 on a linux VM (if you want to try out OM, and haven't installed it, the easiest way to start out can be to just download the OM provided linux VM that includes an installed OM, as well as many libraries including ExternData)

**Comment by tbeu** [comment]
@sjoelund Any ideas?

**Comment by sjoelund** [comment]
There is no such model in the library, but I guess it is due to using something like `xml=xml` when calling a function somewhere. OMC doesn't realize the xml variables come from different scopes and cries wolf.

**Comment by tbeu** [comment]
Switch to branch OM-test please.

The main requirement is that I want to write `xmlfile.getReal("set1.gain.k")` without explictly passing the external object `xml` again to the wrapper function `getReal`.

**Comment by sjoelund** [comment]
But that would break the encapsulation of the function. It can only access constants in that way, right?

**Comment by tbeu** [comment]
Do not know actually.

**Comment by tbeu** [comment]
Function `getReal` is a short class definition where `xml=xml` is already passed. Didn't we have this also in Noise? Is it legal Modelica?

``` mo
final function getReal = Functions.XML.getReal(xml=xml);
```

**Comment by sjoelund** [comment]
I argued it was not legal.

**Comment by tbeu** [comment]
Too bad. Do you have any constructive ideas how to fix it and to make it work in OM?

**Comment by tbeu** [comment]
I updated ExternData.XMLFile.getReal and pushed to the OM-test branch. Can you please check if ExternData.Examples.XMLTest1 works in OM now?

**Comment by hackbarde23** [comment]
I tested the examples, but every samples quits with following error:
The default value of xml causes a cyclic dependency.

OM 1.9.3

**Comment by tbeu** [comment]
Having external objects and short class defined functions with the external object as default argument is not legal in Modelica and not allowed. This is what OpenModelica complains but other tools accept.

Instead of 

``` mo
final function getReal = Functions.XML.getReal(xml=xml) "Get scalar Real value from XML file";
```

the function needs to be rewritten as

``` mo
function getReal "Get scalar Real value from XML file"
  extends Modelica.Icons.Function;
  input String varName;
  input Types.ExternXMLFile xml = xml;
  output Real y;
  algorithm
    y := Functions.XML.Internal.getReal(xml=xml, varName=varName);
  annotation(Inline=true);
end getReal;
```

and called as

``` mo
gain.k = xmlfile.getReal("set1.gain.k", xmlfile.xml);
```

which again accesses the (currently) protected external object `xml` of model `XMLFile`.

To make it valid Modelica I can only think of removing the external objects, which means that when calling

``` mo
gain.k = xmlfile.getReal("/path/to/test.xml", "set1.gain.k");
```

the XML file is opened, parsed, the DOM tree builded etc. This will decrease performance as long as the DOM is not cached. Furthermore it removes the naming compatibility with the proprietary [Modelon.DataAccess](http://www.modelon.com/fileadmin/user_upload/Blog/MaH/MaH_Blog2/Blog2_MaH_5.png) library.

**Comment by tbeu** [comment]
I updated the OM-test branch which should make ExternData.Examples.XMLTest1 working with OpenModelica. Please confirm.

**Comment by hackbarde23** [comment]
The Compilation ends up with errors:

```
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_strtod]+0x14): undefined reference to `_strtod_l'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_strtoi]+0x16): undefined reference to `_strtol_l'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_createXML]+0xbf): undefined reference to `_create_locale'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_destroyXML]+0x28): undefined reference to `_free_locale'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_getDoubleFromXML]+0x40): undefined reference to `_strtod_l'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_getIntFromXML]+0x3a): undefined reference to `_strtol_l'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/ED_XMLFile.lib(LIB Release/ED_XMLFile/ED_XMLFile.obj):(.text[_ED_getDoubleArray1DFromXML]+0xfb): undefined reference to `_strtod_l'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setValueInt]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setValueInt]+0x48): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setValueFloat]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setValueFloat]+0x54): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setSubNodeValueInt]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setSubNodeValueInt]+0xda): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setSubNodeValueFloat]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/bsxml-json.lib(LIB Release/bsxml.obj):(.text[_XmlNode_setSubNodeValueFloat]+0xe6): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_generate_hash_secret_salt]+0x11): undefined reference to `_allrem'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_handleUnknownEncoding]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_handleUnknownEncoding]+0x8f): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_handleUnknownEncoding]+0xe5): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_handleUnknownEncoding]+0x10a): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmlparse.obj):(.text[_startParsing]+0x1a): undefined reference to `_allrem'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncoding]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncoding]+0x5e): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncoding]+0x93): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncoding]+0xbe): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncodingNS]+0xa): undefined reference to `__security_cookie'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncodingNS]+0x5e): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncodingNS]+0x93): undefined reference to `@__security_check_cookie@4'
D:/OpenModelica1.9.3/lib/omlibrary/ExternData 1.0.4-dev/Resources/Library/win32/expat.lib(LIB Release/xmltok.obj):(.text[_findEncodingNS]+0xbe): undefined reference to `@__security_check_cookie@4'
collect2: ld returned 1 exit status
mingw32-make: *** [omc_main_target] Error 1
Compilation process failed. Exited with code 2.
```

**Comment by tbeu** [comment]
Is MinGW really trying to link with the pre-built MSVC libs? This cannot never work out AFAIK. I opened a new [OM ticket](https://trac.openmodelica.org/OpenModelica/ticket/3639) to get more light on this issue.

What you can do now, is, go to the ExternData\ExternData\Resources\C-Sources directory and run `make TARGETDIR="win32"` in your MinGW environment to build the libraries from source. If you then still see the same linker errors delete all .libs files from ExternData\ExternData\Resources\Library\win32 and try again.

**Comment by tbeu** [comment]
Build the libs with `make TARGETDIR="mingw32"`.

**Comment by hackbarde23** [comment]
I am working with OM with a Windows 7 machine, so there is no "make", how can i fix it?

**Comment by tbeu** [comment]
OM comes with MinGW, thus there is a `make`.

Anyway, I updated the OM-test branch where you have the MinGW 32-bit libs.

**Comment by tbeu** [comment]
@hackbarde23 Did you have some successe meanwhile?

**Comment by hackbarde23** [comment]
XMLTest1 works fine!

**Comment by tbeu** [comment]
Thanks for the feedback.

**Comment by tbeu** [comment]
@sjoelund I am kindly asking for your help. I plan to release a new version of ExternData and would like to resolve this issue, especially the MinGW linking on Win. In [om:#3639](https://trac.openmodelica.org/OpenModelica/ticket/3639#comment:1) you proposed to add a autotools BuildProject. There already is a [Makefile](https://github.com/tbeu/ExternData/blob/master/ExternData/Resources/C-Sources/Makefile) that can be used for that. Could you please send a PR to branch `OM-test` that adds such a autotools to the BuildProject directory. Thanks a lot!

**Comment by sjoelund** [comment]
I don't have a Windows installation to test MinGW on. I did try it on Linux though, and it does not pass the frontend due to the following pattern:

``` mo
  model XMLFile "Read data values from XML file"
    parameter String fileName;

    final function getReal = Functions.XML.getReal(xml=local_xml) "Get scalar Real value from XML file";
    protected
      Types.ExternXMLFile local_xml=Types.ExternXMLFile(fileName);
  end XMLFile;

  package Examples "Examples"
    extends Modelica.Icons.ExamplesPackage;
    model XMLTest1
      XMLFile xmlfile(fileName=Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml"));
      initial equation
        gain.k = xmlfile.getReal("set1.gain.k");
    end XMLTest1;
```

I get the wrong prefix for `local_xml` in that case (and for `xml` another error message, but related to not prefixing the name):

``` mo
.ExternData.XMLFile$xmlfile.getReal<function>(String varName, ExternalObject ExternData.Types.ExternXMLFile xml := local_xml) => Real
```

**Comment by tbeu** [comment]
Thanks for testing. Can you switch to branch OM-test where I avoided such a pattern.

**Comment by tbeu** [comment]
@sjoelund Can you the check the autotools script again, as simple as possible please. Thanks.

**Comment by tbeu** [comment]
@sjoelund Could you live with that OM specific function replacements (`ExternData.XMLFile.__OpenModelica_getReal` for `ExternData.XMLFile.getReal`) in the library? I would also need to provide OM specific example models calling these functions then. I know it is not convenient, but at least there is some workaround for OM users available.

**Comment by sjoelund** [comment]
I would rather OM handled the pattern ...

**Comment by tbeu** [comment]
Which is nice. But any idea when you can deal with it?

**Comment by sjoelund** [comment]
No clue. We have a new frontend in the works so probably nobody will look at patching the old frontend to handle this...

**Comment by tbeu** [comment]
And the new frontend can handle such pattern?

**Comment by sjoelund** [comment]
Probably. It does not even handle functions yet ;)

**Comment by tbeu** [comment]
Oh dear.

**Comment by tbeu** [comment]
Maybe it is an easy fix in the old frontend (hoping so).

**Comment by tbeu** [comment]
Wont fix.

**Comment by tbeu** [comment]
At least it is documented in the Readme.

### Known issue with OpenModelica

The example models of the library are known to fail with OpenModelica. However, as a workaround the functions can be rewritten to make them working in OpenModelica by replacing their short class definitions and their appropriate function calls. For example, the short class definition `ExternData.XMLFile.getReal`

``` mo
final function getReal = Functions.XML.getReal(xml=xml)
  "Get scalar Real value from XML file";
```

can be rewritten as function

``` mo
function __OpenModelica_getReal "Get scalar Real value from XML file"
  extends Modelica.Icons.Function;
  input String fileName="" "File where external data is stored"
    annotation(Dialog(loadSelector(filter="XML files (*.xml)", caption="Open file")));
  input String varName "Key";
  output Real y "Real value";
  protected
    Types.ExternXMLFile xml = Types.ExternXMLFile(fileName) "External XML file object";;
  algorithm
    y := Functions.XML.Internal.getReal(xml=xml, varName=varName);
  annotation(Inline=true);
end __OpenModelica_getReal;
```

taking the file name as explicit argument for the external object.

**Comment by tbeu** [comment]
@sjoelund Please check https://gist.github.com/tbeu/b85eb6c5bcb0abb58fb3c5cc818203e7. Does P.B simulate with OMC returning for y.y a constant of 1.0? The difference to the used structure in ExternData is, that P.A.eo is public. So does it work with a public external object instance? Thank you for your support.

**Comment by sjoelund** [comment]
P.A works, P.B does not

**Comment by tbeu** [comment]
Thanks for testing. I will ask at Modelica Trac if calling a.f in P.B is legal.

**Comment by tbeu** [comment]
> Classes derived from  ExternalObject can neither be used in an extends-clause nor in a short class
> definition.

Is this the answer?

**Comment by tbeu** [comment]
Does P.B work with `P.F.f(0.5, a.eo)` for `a.f(0.5)`?

**Comment by sjoelund** [comment]
> Classes derived from ExternalObject can neither be used in an extends-clause nor in a short class
> definition.

Not the answer. Importing external objects is OK.

> Does P.B work with `P.F.f`

No, the issue is simply that OMC gets confused about which eo is referenced.

**Comment by tbeu** [comment]
Thanks for letting me know.

**Comment by Jsilberberg** [comment]
@tbeu  
Hi there, I am pretty new on github and wanna say thanks. 
The Library is very useful. But I would like to use it in OM and unfortunately 
there are troubles. Even with this issue-Thread I can't 
fix it. I tried, with your Example, to get a real Value from a xml file. 
So, I changed the final Function in the model "XMLFile" like in your suggestion:
```mo
function __OpenModelica_getReal "Get scalar Real value from XML file"
      extends Modelica.Icons.Function;
      input String fileName="" "File where external data is stored";
      input String varName "Key";
      output Real y "Real value";
      protected
        ExternData.Types.ExternXMLFile xml = ExternData.Types.ExternXMLFile(fileName) "External XML file object";
      algorithm
        y := ExternData.Functions.XML.Internal.getReal(xml=xml, varName=varName);
      annotation(Inline=true);
end __OpenModelica_getReal;
```
Moreover I simplify the XMLTest file to get only one Value:
```mo
model XMLTest "XML file read test"
  extends Modelica.Icons.Example;
  XMLFile xmlfile(fileName=Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml")) annotation(Placement(transformation(extent={{-80,60},{-60,80}})));
  Real test = xmlfile.__OpenModelica_getReal("modelica://ExternData/Resources/Examples/test.xml","set1.gain.k");
  equation
 annotation(experiment(StopTime=1));
end XMLTest;
```
As you can see the required String input parameter can be found.

After checking the model OM can't find the following function, which can be found in the algorithm section in __OpenModelica_getReal:

ExternData.Functions.XML.Internal.getReal

When I removed ".Internal" the check was successful.
But in the simulation failed. It seems there is a problem in opening the file.

Here are the corresponding Messages:
```
[1] 10:52:16 Translation Notification
[ExternData: 522:7-530:18]: Created directory C:\\Users\\silbju\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_564590

[2] 10:52:16 Translation Notification
[ExternData: 522:7-530:18]: cp -a "D:/OM/ExternData/21.03.17/ExternData-master/ExternData/Resources"/* "C:\\Users\\silbju\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_564590"

[3] 10:52:16 Translation Notification
[ExternData: 522:7-530:18]: Changed directory to C:/Users/silbju/AppData/Local/Temp/omc_compile_ED_XMLFile_564590/BuildProjects/autotools

[4] 10:52:16 Scripting Error
Error opening file: log: No such file or directory.

[5] 10:52:16 Translation Error
[C:/dev/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeFunctionUtil.mo: 742:9-742:129]: Internal error function elaborateFunction failed for function: 
function ExternData.Functions.XML.getReal"Inline never" "Get scalar Real value from XML file"
  input String varName "Key";
  output Real y "Real value";
  input ExternalObject ExternData.Types.ExternXMLFile xml "External XML file object";   external "C" y = ED_getDoubleFromXML(xml, varName);
end ExternData.Functions.XML.getReal; 

[6] 10:52:16 Translation Error
[C:/dev/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeUtil.mo: 620:5-620:83]: Internal error Creation of Modelica functions failed.
```

Can you help me? What is the purpose for ".Internal" in your OM fix?
When I looked up the directory "modelica://ExternData/Resources/Examples/test.xml" , the ExternData folder was named like this: "ExternData 2.2.0". But a change was not successful, too. 

Thank you in forward.

**Comment by tbeu** [comment]
Please try
```mo
model XMLTest "XML file read test"
  extends Modelica.Icons.Example;
  parameter String fileName = Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml");
  Real test = __OpenModelica_getReal(fileName, "set1.gain.k");
  annotation(experiment(StopTime=1));
end XMLTest;
```

**Comment by Jsilberberg** [comment]
No Success. 
__Openmodelica_getReal can't be found. But I think you forgot the xmlfile accidentally.
Even when I add an xmlfile the Error Message is the same. The File/directory cant be found.

Here the Code and the Output of the Message Browser:
```mo
model XMLTest "XML file read test"
  extends Modelica.Icons.Example;
  parameter String fileName = Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml");
  XMLFile xmlfile(fileName);
  Real test = xmlfile.__OpenModelica_getReal(fileName, "set1.gain.k");
  annotation(experiment(StopTime=1));
end XMLTest;
```
```
[1] 19:40:42 Scripting Notification
Check of ExternData.Examples.XMLTest completed successfully.

[1] 19:43:23 Translation Notification
[ExternData: 522:7-530:18]: Created directory C:\\Users\\silbju\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_456426

[2] 19:43:23 Translation Notification
[ExternData: 522:7-530:18]: cp -a "C:/Users/silbju/Downloads/ExternData-master/ExternData/Resources"/* "C:\\Users\\silbju\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_456426"

[3] 19:43:23 Translation Notification
[ExternData: 522:7-530:18]: Changed directory to C:/Users/Julian/AppData/Local/Temp/omc_compile_ED_XMLFile_456426/BuildProjects/autotools

[4] 19:43:23 Scripting Error
Error opening file: log: No such file or directory.

[5] 19:43:23 Translation Error
[C:/OM111/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeFunctionUtil.mo: 791:9-791:129]: Internal error function elaborateFunction failed for function: 
function ExternData.Functions.XML.getReal"Inline never" "Get scalar Real value from XML file"
  input String varName "Key";
  output Real y "Real value";
  input ExternalObject ExternData.Types.ExternXMLFile xml "External XML file object";   external "C" y = ED_getDoubleFromXML(xml, varName);
end ExternData.Functions.XML.getReal; 

[6] 19:43:23 Translation Error
[C:/OM111/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeUtil.mo: 580:5-580:83]: Internal error Creation of Modelica functions failed.
```

**Comment by tbeu** [comment]
Please remove the xmlfile from the model and see my example above. There is no need to define __OpenModelica_getReal within XMLFile.

**Comment by tbeu** [comment]
I checked again and can confirm that the following example works in SimulationX.

```mo
package Test
  extends Modelica.Icons.Package;
  function __OpenModelica_getReal "Get scalar Real value from XML file"
    extends Modelica.Icons.Function;
    input String fileName="" "File where external data is stored";
    input String varName "Key";
    output Real y "Real value";
    protected
      ExternData.Types.ExternXMLFile xml = ExternData.Types.ExternXMLFile(fileName) "External XML file object";
    algorithm
      y := ExternData.Functions.XML.getReal(xml=xml, varName=varName);
    annotation(Inline=false);
  end __OpenModelica_getReal;
  
  model XMLTest "XML file read test"
    extends Modelica.Icons.Example;
    parameter String fileName = Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml");
    Real test = __OpenModelica_getReal(fileName, "set1.gain.k");
    annotation(experiment(StopTime=1));
  end XMLTest;
  annotation(uses(ExternData(version="2.2.0"), Modelica(version="3.2.2")));
end Test;
```
However, it does not work if Inline is true.

**Comment by Jsilberberg** [comment]
So you mean to define a stand alone function __OpenModelica_getReal?

I did this, but I got the same Error.
```mo
model XMLTest "XML file read test"
  extends Modelica.Icons.Example;
  parameter String fileName = Modelica.Utilities.Files.loadResource("modelica://ExternData/Resources/Examples/test.xml");
  Real test = __OpenModelica_getReal(fileName, "set1.gain.k");
  annotation(experiment(StopTime=1));
end XMLTest;
```

**Comment by tbeu** [comment]
Yes, stand-alone. Please try my Test package above.

**Comment by Jsilberberg** [comment]
Oh, sorry. I didnt see this. My mistake. 

It does not work. 
I noticed that OM everytime changed the directory, when I start a simulation.
Because of that there is maybe a conflict? See the translation notifications in the screenshot ([1],[2],[3])
![screen](https://cloud.githubusercontent.com/assets/26637585/24526213/a3ff3608-159d-11e7-97e2-0962e8276be4.png)

I am using the 64-bit Version of OMEdit on Win 7

**Comment by tbeu** [comment]
Sorry, I cannot give OMC support (due to lack of usage). Maybe @sjoelund can guide you.

**Comment by Moksadur** [comment]
@tbeu
Hello, I would like to thank you for ExternData library. It is very useful in Dymola. However, unfortunately, I was not able to use it in OpenModelica even if I have tried the fix that you have suggested. Can you (or someone) please share a version of the example that works in OpenModelica (Maybe a .mo)? That will be very very helpful. Thanks in advance.

**Comment by tbeu** [comment]
The above mentioned package Test (from March 30th) should work. Did you try it? Is it OpenModelica on Linux or Win?

**Comment by Moksadur** [comment]
@tbeu
Thanks for such a quick response. Yes, I have tried that. It gives following errors. It is OpenModelica in Windows 10.

[1] 10:44:56 Translation Notification
[ExternData: 512:7-520:18]: Created directory C:\\Users\\mrn04\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_422688

[2] 10:44:56 Translation Notification
[ExternData: 512:7-520:18]: cp -a "C:/OpenModelica1.12.0-dev-64bit/lib/omlibrary/ExternData 2.2.0/Resources"/* "C:\\Users\\mrn04\\AppData\\Local\\Temp\\/omc_compile_ED_XMLFile_422688"

[3] 10:44:56 Translation Notification
[ExternData: 512:7-520:18]: Changed directory to C:/Users/mrn04/AppData/Local/Temp/omc_compile_ED_XMLFile_422688/BuildProjects/autotools

[4] 10:44:56 Scripting Error
Error opening file: log: No such file or directory.

[5] 10:44:56 Translation Error
[C:/dev/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeFunctionUtil.mo: 742:9-742:129]: Internal error function elaborateFunction failed for function: 
function ExternData.Functions.XML.getReal"Inline never" "Get scalar Real value from XML file"
  input String varName "Key";
  output Real y "Real value";
  input ExternalObject ExternData.Types.ExternXMLFile xml "External XML file object";   external "C" y = ED_getDoubleFromXML(xml, varName);
end ExternData.Functions.XML.getReal; 

[6] 10:44:56 Translation Error
[C:/dev/OpenModelica64bit/OMCompiler/Compiler/SimCode/SimCodeUtil.mo: 603:5-603:83]: Internal error Creation of Modelica functions failed.

**Comment by tbeu** [comment]
@sjoelund Do you have any idea what goes wrong here?

**Comment by tbeu** [comment]
@Moksadur You still can try to open a new ticket at the OM issue tracker: https://trac.openmodelica.org/OpenModelica/newticket

**Comment by Moksadur** [comment]
@tbeu
I have raised a [ticket](https://trac.openmodelica.org/OpenModelica/ticket/4448). Let's see what happens. Meanwhile, please inform me if you figure out something. Thanks a lot.
